apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fxgued5uo-nodejs 
  janus-idp.io/tekton: fxgued5uo-nodejs
  backstage.io/kubernetes-id: fxgued5uo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fxgued5uo-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  