apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fxgued5uo-nodejs
  janus-idp.io/tekton: fxgued5uo-nodejs
  backstage.io/kubernetes-id: fxgued5uo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fxgued5uo-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
